SCRIPT_NAME=elf
OUTPUT_FORMAT="elf32-i386"
TEXT_START_ADDR=0x08048000
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
COMMONPAGESIZE="CONSTANT (COMMONPAGESIZE)"
ARCH=i386
MACHINE=
NOP=0x90909090
TEMPLATE_NAME=elf32
GENERATE_SHLIB_SCRIPT=yes
GENERATE_PIE_SCRIPT=yes
NO_SMALL_DATA=yes
SEPARATE_GOTPLT=12

# In Gentoo, we install 32bit libs into /lib32 in an
# ABI setup with amd64/x86
case "$target" in
  x86_64*-linux*)
    case "$EMULATION_NAME" in
      *i386*) LIBPATH_SUFFIX=32  ;;
    esac
  ;;
esac
