ccflags-y+=-I$(CONFIG_INFRA_PATH)/include
ccflags-y+=-I$(CONFIG_STGFB_PATH)/include
ccflags-y+=-I$(TREE_ROOT)/linux/stmedia/
ccflags-y+=-I$(TREE_ROOT)/linux/include
ccflags-y+=-Werror

stm_v4l2_vxi-objs := stm_extin_vxi.o
obj-m += stm_v4l2_vxi.o

