
#ifndef _HEVC_HWPE_DEBUG_H_
#define _HEVC_HWPE_DEBUG_H_

/****************************************************************************************
*                     Copyright STMicroelectronics
*              All rights reserved, COMPANY CONFIDENTIAL
*     Unauthorized reproduction and communication strictly prohibited
*----------------------------------------------------------------------------------------
*                   System Platforms Group - IP&Design/SPG
*----------------------------------------------------------------------------------------
*  This C header file was automatically generated by 'spirit2regtest' utility from the
*  SPIRIT description of the component.
*
*  Purpose : It declares C preprocessor definitions for component, register and 
*            register fields parameters
*
*  Generated by spirit2regtest v2.4.1
*
*  PLEASE DO NOT MODIFY THIS FILE
****************************************************************************************/


/*!
* \brief
* Component section
* Purpose : defines macros for component
*           specific informations
*/

#define HEVC_HWPE_DEBUG_VENDOR                                      ("st.com")
#define HEVC_HWPE_DEBUG_LIBRARY                                     ("UPD")
#define HEVC_HWPE_DEBUG_NAME                                        ("HEVC_HWPE_DEBUG")
#define HEVC_HWPE_DEBUG_VERSION                                     ("1.0")

/*!
* \brief
* Address Block : C8HAD1_HWPE_DEBUG
*/

#define HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR                 (0x0)

/*!
* \brief
* Register : CRC_SLICMD
*/

#define HEVC_HWPE_DEBUG_CRC_SLICMD_SIZE                             (32)
#define HEVC_HWPE_DEBUG_CRC_SLICMD_OFFSET                           (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x0)
#define HEVC_HWPE_DEBUG_CRC_SLICMD_RESET_VALUE                      (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_SLICMD_BITFIELD_MASK                    (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_SLICMD_RWMASK                           (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_SLICMD_ROMASK                           (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_SLICMD_WOMASK                           (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_SLICMD_UNUSED_MASK                      (0x00000000)

/*!
* \brief
* Bit-field : crc_slicmd
*/

#define HEVC_HWPE_DEBUG_CRC_SLICMD_crc_slicmd_OFFSET                (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_SLICMD_crc_slicmd_WIDTH                 (32)
#define HEVC_HWPE_DEBUG_CRC_SLICMD_crc_slicmd_MASK                  (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_CTBCMD
*/

#define HEVC_HWPE_DEBUG_CRC_CTBCMD_SIZE                             (32)
#define HEVC_HWPE_DEBUG_CRC_CTBCMD_OFFSET                           (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x4)
#define HEVC_HWPE_DEBUG_CRC_CTBCMD_RESET_VALUE                      (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_CTBCMD_BITFIELD_MASK                    (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_CTBCMD_RWMASK                           (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_CTBCMD_ROMASK                           (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_CTBCMD_WOMASK                           (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_CTBCMD_UNUSED_MASK                      (0x00000000)

/*!
* \brief
* Bit-field : crc_ctbcmd
*/

#define HEVC_HWPE_DEBUG_CRC_CTBCMD_crc_ctbcmd_OFFSET                (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_CTBCMD_crc_ctbcmd_WIDTH                 (32)
#define HEVC_HWPE_DEBUG_CRC_CTBCMD_crc_ctbcmd_MASK                  (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_RESDATA
*/

#define HEVC_HWPE_DEBUG_CRC_RESDATA_SIZE                            (32)
#define HEVC_HWPE_DEBUG_CRC_RESDATA_OFFSET                          (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x8)
#define HEVC_HWPE_DEBUG_CRC_RESDATA_RESET_VALUE                     (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RESDATA_BITFIELD_MASK                   (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_RESDATA_RWMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RESDATA_ROMASK                          (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_RESDATA_WOMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RESDATA_UNUSED_MASK                     (0x00000000)

/*!
* \brief
* Bit-field : crc_res_data
*/

#define HEVC_HWPE_DEBUG_CRC_RESDATA_crc_res_data_OFFSET             (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RESDATA_crc_res_data_WIDTH              (32)
#define HEVC_HWPE_DEBUG_CRC_RESDATA_crc_res_data_MASK               (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_HWCFG_RED
*/

#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_SIZE                          (32)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_OFFSET                        (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0xc)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_RESET_VALUE                   (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_BITFIELD_MASK                 (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_RWMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_ROMASK                        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_WOMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_UNUSED_MASK                   (0x00000000)

/*!
* \brief
* Bit-field : crc_hwcfg_red
*/

#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_crc_hwcfg_red_OFFSET          (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_crc_hwcfg_red_WIDTH           (32)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_RED_crc_hwcfg_red_MASK            (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_HWCFG_MVPRED
*/

#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_SIZE                       (32)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_OFFSET                     (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x10)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_RESET_VALUE                (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_BITFIELD_MASK              (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_RWMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_ROMASK                     (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_WOMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_UNUSED_MASK                (0x00000000)

/*!
* \brief
* Bit-field : crc_hwcfg_mvpred
*/

#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_crc_hwcfg_mvpred_OFFSET    (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_crc_hwcfg_mvpred_WIDTH     (32)
#define HEVC_HWPE_DEBUG_CRC_HWCFG_MVPRED_crc_hwcfg_mvpred_MASK      (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_MVPRED_XPREDMAC
*/

#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_SIZE                    (32)
#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_OFFSET                  (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x14)
#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_RESET_VALUE             (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_BITFIELD_MASK           (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_RWMASK                  (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_ROMASK                  (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_WOMASK                  (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_UNUSED_MASK             (0x00000000)

/*!
* \brief
* Bit-field : crc_mvpred_xpredmac
*/

#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_crc_mvpred_xpredmac_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_crc_mvpred_xpredmac_WIDTH (32)
#define HEVC_HWPE_DEBUG_CRC_MVPRED_XPREDMAC_crc_mvpred_xpredmac_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_XPREDMAC_XPREDOP_CMD
*/

#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_SIZE               (32)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_OFFSET             (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x18)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_RESET_VALUE        (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_BITFIELD_MASK      (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_RWMASK             (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_ROMASK             (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_WOMASK             (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_UNUSED_MASK        (0x00000000)

/*!
* \brief
* Bit-field : crc_xpredmac_xpredop_cmd
*/

#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_crc_xpredmac_xpredop_cmd_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_crc_xpredmac_xpredop_cmd_WIDTH (32)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_CMD_crc_xpredmac_xpredop_cmd_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_XPREDMAC_XPREDOP_DATA
*/

#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_SIZE              (32)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_OFFSET            (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x1c)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_RESET_VALUE       (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_BITFIELD_MASK     (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_RWMASK            (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_ROMASK            (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_WOMASK            (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_UNUSED_MASK       (0x00000000)

/*!
* \brief
* Bit-field : crc_xpredmac_xpredop_data
*/

#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_crc_xpredmac_xpredop_data_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_crc_xpredmac_xpredop_data_WIDTH (32)
#define HEVC_HWPE_DEBUG_CRC_XPREDMAC_XPREDOP_DATA_crc_xpredmac_xpredop_data_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_XPREDOP_IPRED_CMD
*/

#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_SIZE                  (32)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_OFFSET                (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x20)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_RESET_VALUE           (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_BITFIELD_MASK         (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_RWMASK                (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_ROMASK                (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_WOMASK                (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_UNUSED_MASK           (0x00000000)

/*!
* \brief
* Bit-field : crc_xpredop_ipred_cmd
*/

#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_crc_xpredop_ipred_cmd_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_crc_xpredop_ipred_cmd_WIDTH (32)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_CMD_crc_xpredop_ipred_cmd_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_XPREDOP_IPRED_DATA
*/

#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_SIZE                 (32)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_OFFSET               (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x24)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_RESET_VALUE          (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_BITFIELD_MASK        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_RWMASK               (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_ROMASK               (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_WOMASK               (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_UNUSED_MASK          (0x00000000)

/*!
* \brief
* Bit-field : crc_xpredop_ipred_data
*/

#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_crc_xpredop_ipred_data_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_crc_xpredop_ipred_data_WIDTH (32)
#define HEVC_HWPE_DEBUG_CRC_XPREDOP_IPRED_DATA_crc_xpredop_ipred_data_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_RED_PIPE_CMD
*/

#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_SIZE                       (32)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_OFFSET                     (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x28)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_RESET_VALUE                (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_BITFIELD_MASK              (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_RWMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_ROMASK                     (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_WOMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_UNUSED_MASK                (0x00000000)

/*!
* \brief
* Bit-field : crc_red_pipe_cmd
*/

#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_crc_red_pipe_cmd_OFFSET    (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_crc_red_pipe_cmd_WIDTH     (32)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_CMD_crc_red_pipe_cmd_MASK      (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_RED_PIPE_DATA
*/

#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_SIZE                      (32)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_OFFSET                    (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x2c)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_RESET_VALUE               (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_BITFIELD_MASK             (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_RWMASK                    (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_ROMASK                    (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_WOMASK                    (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_UNUSED_MASK               (0x00000000)

/*!
* \brief
* Bit-field : crc_red_pipe_data
*/

#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_crc_red_pipe_data_OFFSET  (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_crc_red_pipe_data_WIDTH   (32)
#define HEVC_HWPE_DEBUG_CRC_RED_PIPE_DATA_crc_red_pipe_data_MASK    (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_PIPE_IPRED_CMD
*/

#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_SIZE                     (32)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_OFFSET                   (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x30)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_RESET_VALUE              (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_BITFIELD_MASK            (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_RWMASK                   (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_ROMASK                   (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_WOMASK                   (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_UNUSED_MASK              (0x00000000)

/*!
* \brief
* Bit-field : crc_pipe_ipred_cmd
*/

#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_crc_pipe_ipred_cmd_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_crc_pipe_ipred_cmd_WIDTH (32)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_CMD_crc_pipe_ipred_cmd_MASK  (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_PIPE_IPRED_DATA
*/

#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_SIZE                    (32)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_OFFSET                  (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x34)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_RESET_VALUE             (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_BITFIELD_MASK           (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_RWMASK                  (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_ROMASK                  (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_WOMASK                  (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_UNUSED_MASK             (0x00000000)

/*!
* \brief
* Bit-field : crc_pipe_ipred_data
*/

#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_crc_pipe_ipred_data_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_crc_pipe_ipred_data_WIDTH (32)
#define HEVC_HWPE_DEBUG_CRC_PIPE_IPRED_DATA_crc_pipe_ipred_data_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_IPRED_OUT_CMD
*/

#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_SIZE                      (32)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_OFFSET                    (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x38)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_RESET_VALUE               (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_BITFIELD_MASK             (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_RWMASK                    (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_ROMASK                    (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_WOMASK                    (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_UNUSED_MASK               (0x00000000)

/*!
* \brief
* Bit-field : crc_ipredout_cmd
*/

#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_crc_ipredout_cmd_OFFSET   (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_crc_ipredout_cmd_WIDTH    (32)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_CMD_crc_ipredout_cmd_MASK     (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_IPRED_OUT_DATA
*/

#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_SIZE                     (32)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_OFFSET                   (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x3c)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_RESET_VALUE              (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_BITFIELD_MASK            (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_RWMASK                   (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_ROMASK                   (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_WOMASK                   (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_UNUSED_MASK              (0x00000000)

/*!
* \brief
* Bit-field : crc_ipredout_data
*/

#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_crc_ipredout_data_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_crc_ipredout_data_WIDTH  (32)
#define HEVC_HWPE_DEBUG_CRC_IPRED_OUT_DATA_crc_ipredout_data_MASK   (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_PPBIN
*/

#define HEVC_HWPE_DEBUG_CRC_PPBIN_SIZE                              (32)
#define HEVC_HWPE_DEBUG_CRC_PPBIN_OFFSET                            (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x40)
#define HEVC_HWPE_DEBUG_CRC_PPBIN_RESET_VALUE                       (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PPBIN_BITFIELD_MASK                     (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_PPBIN_RWMASK                            (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PPBIN_ROMASK                            (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_PPBIN_WOMASK                            (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PPBIN_UNUSED_MASK                       (0x00000000)

/*!
* \brief
* Bit-field : crc_ppbin
*/

#define HEVC_HWPE_DEBUG_CRC_PPBIN_crc_ppbin_OFFSET                  (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PPBIN_crc_ppbin_WIDTH                   (32)
#define HEVC_HWPE_DEBUG_CRC_PPBIN_crc_ppbin_MASK                    (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_PPBOUT
*/

#define HEVC_HWPE_DEBUG_CRC_PPBOUT_SIZE                             (32)
#define HEVC_HWPE_DEBUG_CRC_PPBOUT_OFFSET                           (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x44)
#define HEVC_HWPE_DEBUG_CRC_PPBOUT_RESET_VALUE                      (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PPBOUT_BITFIELD_MASK                    (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_PPBOUT_RWMASK                           (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PPBOUT_ROMASK                           (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_PPBOUT_WOMASK                           (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PPBOUT_UNUSED_MASK                      (0x00000000)

/*!
* \brief
* Bit-field : crc_ppbout
*/

#define HEVC_HWPE_DEBUG_CRC_PPBOUT_crc_ppbout_OFFSET                (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_PPBOUT_crc_ppbout_WIDTH                 (32)
#define HEVC_HWPE_DEBUG_CRC_PPBOUT_crc_ppbout_MASK                  (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_DEB_SAO_CMD
*/

#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_SIZE                        (32)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_OFFSET                      (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x48)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_RESET_VALUE                 (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_BITFIELD_MASK               (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_RWMASK                      (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_ROMASK                      (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_WOMASK                      (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_UNUSED_MASK                 (0x00000000)

/*!
* \brief
* Bit-field : crc_deb_sao_cmd
*/

#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_crc_deb_sao_cmd_OFFSET      (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_crc_deb_sao_cmd_WIDTH       (32)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_CMD_crc_deb_sao_cmd_MASK        (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_DEB_SAO_DATA
*/

#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_SIZE                       (32)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_OFFSET                     (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x4c)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_RESET_VALUE                (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_BITFIELD_MASK              (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_RWMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_ROMASK                     (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_WOMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_UNUSED_MASK                (0x00000000)

/*!
* \brief
* Bit-field : crc_deb_sao_data
*/

#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_crc_deb_sao_data_OFFSET    (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_crc_deb_sao_data_WIDTH     (32)
#define HEVC_HWPE_DEBUG_CRC_DEB_SAO_DATA_crc_deb_sao_data_MASK      (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_SAO_OUT
*/

#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_SIZE                            (32)
#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_OFFSET                          (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x50)
#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_RESET_VALUE                     (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_BITFIELD_MASK                   (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_RWMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_ROMASK                          (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_WOMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_UNUSED_MASK                     (0x00000000)

/*!
* \brief
* Bit-field : crc_sao_out
*/

#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_crc_sao_out_OFFSET              (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_crc_sao_out_WIDTH               (32)
#define HEVC_HWPE_DEBUG_CRC_SAO_OUT_crc_sao_out_MASK                (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_RESIZE_OUT
*/

#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_SIZE                         (32)
#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_OFFSET                       (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x54)
#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_RESET_VALUE                  (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_BITFIELD_MASK                (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_RWMASK                       (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_ROMASK                       (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_WOMASK                       (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_UNUSED_MASK                  (0x00000000)

/*!
* \brief
* Bit-field : crc_resize_out
*/

#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_crc_resize_out_OFFSET        (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_crc_resize_out_WIDTH         (32)
#define HEVC_HWPE_DEBUG_CRC_RESIZE_OUT_crc_resize_out_MASK          (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_OUT_REF
*/

#define HEVC_HWPE_DEBUG_CRC_OUT_REF_SIZE                            (32)
#define HEVC_HWPE_DEBUG_CRC_OUT_REF_OFFSET                          (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x58)
#define HEVC_HWPE_DEBUG_CRC_OUT_REF_RESET_VALUE                     (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_REF_BITFIELD_MASK                   (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_OUT_REF_RWMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_REF_ROMASK                          (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_OUT_REF_WOMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_REF_UNUSED_MASK                     (0x00000000)

/*!
* \brief
* Bit-field : crc_out_ref
*/

#define HEVC_HWPE_DEBUG_CRC_OUT_REF_crc_out_ref_OFFSET              (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_REF_crc_out_ref_WIDTH               (32)
#define HEVC_HWPE_DEBUG_CRC_OUT_REF_crc_out_ref_MASK                (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_OUT_DISP
*/

#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_SIZE                           (32)
#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_OFFSET                         (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x5c)
#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_RESET_VALUE                    (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_BITFIELD_MASK                  (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_RWMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_ROMASK                         (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_WOMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_UNUSED_MASK                    (0x00000000)

/*!
* \brief
* Bit-field : crc_out_disp
*/

#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_crc_out_disp_OFFSET            (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_crc_out_disp_WIDTH             (32)
#define HEVC_HWPE_DEBUG_CRC_OUT_DISP_crc_out_disp_MASK              (0xFFFFFFFF)

/*!
* \brief
* Register : CRC_OUT_DECIM
*/

#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_SIZE                          (32)
#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_OFFSET                        (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x60)
#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_RESET_VALUE                   (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_BITFIELD_MASK                 (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_RWMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_ROMASK                        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_WOMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_UNUSED_MASK                   (0x00000000)

/*!
* \brief
* Bit-field : crc_out_decim
*/

#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_crc_out_decim_OFFSET          (0x00000000)
#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_crc_out_decim_WIDTH           (32)
#define HEVC_HWPE_DEBUG_CRC_OUT_DECIM_crc_out_decim_MASK            (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_RED_0
*/

#define HEVC_HWPE_DEBUG_STATUS_RED_0_SIZE                           (32)
#define HEVC_HWPE_DEBUG_STATUS_RED_0_OFFSET                         (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x64)
#define HEVC_HWPE_DEBUG_STATUS_RED_0_RESET_VALUE                    (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RED_0_BITFIELD_MASK                  (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_RED_0_RWMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RED_0_ROMASK                         (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_RED_0_WOMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RED_0_UNUSED_MASK                    (0x00000000)

/*!
* \brief
* Bit-field : red_status_0
*/

#define HEVC_HWPE_DEBUG_STATUS_RED_0_red_status_0_OFFSET            (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RED_0_red_status_0_WIDTH             (32)
#define HEVC_HWPE_DEBUG_STATUS_RED_0_red_status_0_MASK              (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_RED_1
*/

#define HEVC_HWPE_DEBUG_STATUS_RED_1_SIZE                           (32)
#define HEVC_HWPE_DEBUG_STATUS_RED_1_OFFSET                         (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x68)
#define HEVC_HWPE_DEBUG_STATUS_RED_1_RESET_VALUE                    (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RED_1_BITFIELD_MASK                  (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_RED_1_RWMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RED_1_ROMASK                         (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_RED_1_WOMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RED_1_UNUSED_MASK                    (0x00000000)

/*!
* \brief
* Bit-field : red_status_1
*/

#define HEVC_HWPE_DEBUG_STATUS_RED_1_red_status_1_OFFSET            (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RED_1_red_status_1_WIDTH             (32)
#define HEVC_HWPE_DEBUG_STATUS_RED_1_red_status_1_MASK              (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_PIPE_0
*/

#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_SIZE                          (32)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_OFFSET                        (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x6c)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_RESET_VALUE                   (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_BITFIELD_MASK                 (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_RWMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_ROMASK                        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_WOMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_UNUSED_MASK                   (0x00000000)

/*!
* \brief
* Bit-field : pipe_status_0
*/

#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_pipe_status_0_OFFSET          (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_pipe_status_0_WIDTH           (32)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_0_pipe_status_0_MASK            (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_PIPE_1
*/

#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_SIZE                          (32)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_OFFSET                        (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x70)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_RESET_VALUE                   (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_BITFIELD_MASK                 (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_RWMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_ROMASK                        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_WOMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_UNUSED_MASK                   (0x00000000)

/*!
* \brief
* Bit-field : pipe_status_1
*/

#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_pipe_status_1_OFFSET          (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_pipe_status_1_WIDTH           (32)
#define HEVC_HWPE_DEBUG_STATUS_PIPE_1_pipe_status_1_MASK            (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_IPRED
*/

#define HEVC_HWPE_DEBUG_STATUS_IPRED_SIZE                           (32)
#define HEVC_HWPE_DEBUG_STATUS_IPRED_OFFSET                         (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x74)
#define HEVC_HWPE_DEBUG_STATUS_IPRED_RESET_VALUE                    (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_IPRED_BITFIELD_MASK                  (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_IPRED_RWMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_IPRED_ROMASK                         (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_IPRED_WOMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_IPRED_UNUSED_MASK                    (0x00000000)

/*!
* \brief
* Bit-field : ipred_status
*/

#define HEVC_HWPE_DEBUG_STATUS_IPRED_ipred_status_OFFSET            (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_IPRED_ipred_status_WIDTH             (32)
#define HEVC_HWPE_DEBUG_STATUS_IPRED_ipred_status_MASK              (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_MVPRED
*/

#define HEVC_HWPE_DEBUG_STATUS_MVPRED_SIZE                          (32)
#define HEVC_HWPE_DEBUG_STATUS_MVPRED_OFFSET                        (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x78)
#define HEVC_HWPE_DEBUG_STATUS_MVPRED_RESET_VALUE                   (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_MVPRED_BITFIELD_MASK                 (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_MVPRED_RWMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_MVPRED_ROMASK                        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_MVPRED_WOMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_MVPRED_UNUSED_MASK                   (0x00000000)

/*!
* \brief
* Bit-field : mvpred_status
*/

#define HEVC_HWPE_DEBUG_STATUS_MVPRED_mvpred_status_OFFSET          (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_MVPRED_mvpred_status_WIDTH           (32)
#define HEVC_HWPE_DEBUG_STATUS_MVPRED_mvpred_status_MASK            (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_HWCFG
*/

#define HEVC_HWPE_DEBUG_STATUS_HWCFG_SIZE                           (32)
#define HEVC_HWPE_DEBUG_STATUS_HWCFG_OFFSET                         (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x7c)
#define HEVC_HWPE_DEBUG_STATUS_HWCFG_RESET_VALUE                    (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_HWCFG_BITFIELD_MASK                  (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_HWCFG_RWMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_HWCFG_ROMASK                         (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_HWCFG_WOMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_HWCFG_UNUSED_MASK                    (0x00000000)

/*!
* \brief
* Bit-field : hwcfg_status
*/

#define HEVC_HWPE_DEBUG_STATUS_HWCFG_hwcfg_status_OFFSET            (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_HWCFG_hwcfg_status_WIDTH             (32)
#define HEVC_HWPE_DEBUG_STATUS_HWCFG_hwcfg_status_MASK              (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_XPREDMAC_CMD_0
*/

#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_SIZE                  (32)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_OFFSET                (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x80)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_RESET_VALUE           (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_BITFIELD_MASK         (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_RWMASK                (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_ROMASK                (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_WOMASK                (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_UNUSED_MASK           (0x00000000)

/*!
* \brief
* Bit-field : xpredmac_cmd_status_0
*/

#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_xpredmac_cmd_status_0_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_xpredmac_cmd_status_0_WIDTH (32)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_0_xpredmac_cmd_status_0_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_XPREDMAC_CMD_1
*/

#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_SIZE                  (32)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_OFFSET                (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x84)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_RESET_VALUE           (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_BITFIELD_MASK         (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_RWMASK                (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_ROMASK                (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_WOMASK                (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_UNUSED_MASK           (0x00000000)

/*!
* \brief
* Bit-field : xpredmac_cmd_status_1
*/

#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_xpredmac_cmd_status_1_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_xpredmac_cmd_status_1_WIDTH (32)
#define HEVC_HWPE_DEBUG_STATUS_XPREDMAC_CMD_1_xpredmac_cmd_status_1_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_XPREDOP_0
*/

#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_SIZE                       (32)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_OFFSET                     (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x88)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_RESET_VALUE                (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_BITFIELD_MASK              (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_RWMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_ROMASK                     (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_WOMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_UNUSED_MASK                (0x00000000)

/*!
* \brief
* Bit-field : xpredop_status_0
*/

#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_xpredop_status_0_OFFSET    (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_xpredop_status_0_WIDTH     (32)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_0_xpredop_status_0_MASK      (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_XPREDOP_1
*/

#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_SIZE                       (32)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_OFFSET                     (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x8c)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_RESET_VALUE                (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_BITFIELD_MASK              (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_RWMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_ROMASK                     (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_WOMASK                     (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_UNUSED_MASK                (0x00000000)

/*!
* \brief
* Bit-field : xpredop_status_1
*/

#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_xpredop_status_1_OFFSET    (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_xpredop_status_1_WIDTH     (32)
#define HEVC_HWPE_DEBUG_STATUS_XPREDOP_1_xpredop_status_1_MASK      (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_DBK
*/

#define HEVC_HWPE_DEBUG_STATUS_DBK_SIZE                             (32)
#define HEVC_HWPE_DEBUG_STATUS_DBK_OFFSET                           (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x90)
#define HEVC_HWPE_DEBUG_STATUS_DBK_RESET_VALUE                      (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_DBK_BITFIELD_MASK                    (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_DBK_RWMASK                           (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_DBK_ROMASK                           (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_DBK_WOMASK                           (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_DBK_UNUSED_MASK                      (0x00000000)

/*!
* \brief
* Bit-field : dbk_status
*/

#define HEVC_HWPE_DEBUG_STATUS_DBK_dbk_status_OFFSET                (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_DBK_dbk_status_WIDTH                 (32)
#define HEVC_HWPE_DEBUG_STATUS_DBK_dbk_status_MASK                  (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_RESIZE
*/

#define HEVC_HWPE_DEBUG_STATUS_RESIZE_SIZE                          (32)
#define HEVC_HWPE_DEBUG_STATUS_RESIZE_OFFSET                        (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x94)
#define HEVC_HWPE_DEBUG_STATUS_RESIZE_RESET_VALUE                   (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RESIZE_BITFIELD_MASK                 (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_RESIZE_RWMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RESIZE_ROMASK                        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_RESIZE_WOMASK                        (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RESIZE_UNUSED_MASK                   (0x00000000)

/*!
* \brief
* Bit-field : resize_status
*/

#define HEVC_HWPE_DEBUG_STATUS_RESIZE_resize_status_OFFSET          (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_RESIZE_resize_status_WIDTH           (32)
#define HEVC_HWPE_DEBUG_STATUS_RESIZE_resize_status_MASK            (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_GENERAL_0_HWPE0
*/

#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_SIZE                 (32)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_OFFSET               (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x98)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_RESET_VALUE          (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_BITFIELD_MASK        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_RWMASK               (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_ROMASK               (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_WOMASK               (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_UNUSED_MASK          (0x00000000)

/*!
* \brief
* Bit-field : hwpe_general_hwpe0_status0
*/

#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_hwpe_general_hwpe0_status0_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_hwpe_general_hwpe0_status0_WIDTH (32)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE0_hwpe_general_hwpe0_status0_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_GENERAL_1_HWPE0
*/

#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_SIZE                 (32)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_OFFSET               (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0x9c)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_RESET_VALUE          (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_BITFIELD_MASK        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_RWMASK               (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_ROMASK               (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_WOMASK               (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_UNUSED_MASK          (0x00000000)

/*!
* \brief
* Bit-field : hwpe_general_hwpe0_status1
*/

#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_hwpe_general_hwpe0_status1_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_hwpe_general_hwpe0_status1_WIDTH (32)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_1_HWPE0_hwpe_general_hwpe0_status1_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : STATUS_GENERAL_0_HWPE1
*/

#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_SIZE                 (32)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_OFFSET               (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0xa0)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_RESET_VALUE          (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_BITFIELD_MASK        (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_RWMASK               (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_ROMASK               (0xFFFFFFFF)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_WOMASK               (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_UNUSED_MASK          (0x00000000)

/*!
* \brief
* Bit-field : hwpe_general_hwpe1_status0
*/

#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_hwpe_general_hwpe1_status0_OFFSET (0x00000000)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_hwpe_general_hwpe1_status0_WIDTH (32)
#define HEVC_HWPE_DEBUG_STATUS_GENERAL_0_HWPE1_hwpe_general_hwpe1_status0_MASK (0xFFFFFFFF)

/*!
* \brief
* Register : MCC_HIT
*/

#define HEVC_HWPE_DEBUG_MCC_HIT_SIZE                                (32)
#define HEVC_HWPE_DEBUG_MCC_HIT_OFFSET                              (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0xa4)
#define HEVC_HWPE_DEBUG_MCC_HIT_RESET_VALUE                         (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_HIT_BITFIELD_MASK                       (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_HIT_RWMASK                              (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_HIT_ROMASK                              (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_HIT_WOMASK                              (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_HIT_UNUSED_MASK                         (0xFE000000)

/*!
* \brief
* Bit-field : mcc_hit_cnt
*/

#define HEVC_HWPE_DEBUG_MCC_HIT_mcc_hit_cnt_OFFSET                  (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_HIT_mcc_hit_cnt_WIDTH                   (25)
#define HEVC_HWPE_DEBUG_MCC_HIT_mcc_hit_cnt_MASK                    (0x01FFFFFF)

/*!
* \brief
* Register : MCC_OUT_LD16
*/

#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_SIZE                           (32)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_OFFSET                         (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0xa8)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_RESET_VALUE                    (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_BITFIELD_MASK                  (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_RWMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_ROMASK                         (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_WOMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_UNUSED_MASK                    (0xFE000000)

/*!
* \brief
* Bit-field : mcc_out_ld16_cnt
*/

#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_mcc_out_ld16_cnt_OFFSET        (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_mcc_out_ld16_cnt_WIDTH         (25)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD16_mcc_out_ld16_cnt_MASK          (0x01FFFFFF)

/*!
* \brief
* Register : MCC_OUT_LD32
*/

#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_SIZE                           (32)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_OFFSET                         (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0xac)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_RESET_VALUE                    (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_BITFIELD_MASK                  (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_RWMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_ROMASK                         (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_WOMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_UNUSED_MASK                    (0xFE000000)

/*!
* \brief
* Bit-field : mcc_out_ld32_cnt
*/

#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_mcc_out_ld32_cnt_OFFSET        (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_mcc_out_ld32_cnt_WIDTH         (25)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD32_mcc_out_ld32_cnt_MASK          (0x01FFFFFF)

/*!
* \brief
* Register : MCC_OUT_LD64
*/

#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_SIZE                           (32)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_OFFSET                         (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0xb0)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_RESET_VALUE                    (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_BITFIELD_MASK                  (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_RWMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_ROMASK                         (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_WOMASK                         (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_UNUSED_MASK                    (0xFE000000)

/*!
* \brief
* Bit-field : mcc_out_ld64_cnt
*/

#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_mcc_out_ld64_cnt_OFFSET        (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_mcc_out_ld64_cnt_WIDTH         (25)
#define HEVC_HWPE_DEBUG_MCC_OUT_LD64_mcc_out_ld64_cnt_MASK          (0x01FFFFFF)

/*!
* \brief
* Register : MCC_IN_LD16
*/

#define HEVC_HWPE_DEBUG_MCC_IN_LD16_SIZE                            (32)
#define HEVC_HWPE_DEBUG_MCC_IN_LD16_OFFSET                          (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0xb4)
#define HEVC_HWPE_DEBUG_MCC_IN_LD16_RESET_VALUE                     (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD16_BITFIELD_MASK                   (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_IN_LD16_RWMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD16_ROMASK                          (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_IN_LD16_WOMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD16_UNUSED_MASK                     (0xFE000000)

/*!
* \brief
* Bit-field : mcc_in_ld16_cnt
*/

#define HEVC_HWPE_DEBUG_MCC_IN_LD16_mcc_in_ld16_cnt_OFFSET          (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD16_mcc_in_ld16_cnt_WIDTH           (25)
#define HEVC_HWPE_DEBUG_MCC_IN_LD16_mcc_in_ld16_cnt_MASK            (0x01FFFFFF)

/*!
* \brief
* Register : MCC_IN_LD32
*/

#define HEVC_HWPE_DEBUG_MCC_IN_LD32_SIZE                            (32)
#define HEVC_HWPE_DEBUG_MCC_IN_LD32_OFFSET                          (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0xb8)
#define HEVC_HWPE_DEBUG_MCC_IN_LD32_RESET_VALUE                     (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD32_BITFIELD_MASK                   (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_IN_LD32_RWMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD32_ROMASK                          (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_IN_LD32_WOMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD32_UNUSED_MASK                     (0xFE000000)

/*!
* \brief
* Bit-field : mcc_in_ld32_cnt
*/

#define HEVC_HWPE_DEBUG_MCC_IN_LD32_mcc_in_ld32_cnt_OFFSET          (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD32_mcc_in_ld32_cnt_WIDTH           (25)
#define HEVC_HWPE_DEBUG_MCC_IN_LD32_mcc_in_ld32_cnt_MASK            (0x01FFFFFF)

/*!
* \brief
* Register : MCC_IN_LD64
*/

#define HEVC_HWPE_DEBUG_MCC_IN_LD64_SIZE                            (32)
#define HEVC_HWPE_DEBUG_MCC_IN_LD64_OFFSET                          (HEVC_HWPE_DEBUG_C8HAD1_HWPE_DEBUG_BASE_ADDR + 0xbc)
#define HEVC_HWPE_DEBUG_MCC_IN_LD64_RESET_VALUE                     (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD64_BITFIELD_MASK                   (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_IN_LD64_RWMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD64_ROMASK                          (0x01FFFFFF)
#define HEVC_HWPE_DEBUG_MCC_IN_LD64_WOMASK                          (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD64_UNUSED_MASK                     (0xFE000000)

/*!
* \brief
* Bit-field : mcc_in_ld64_cnt
*/

#define HEVC_HWPE_DEBUG_MCC_IN_LD64_mcc_in_ld64_cnt_OFFSET          (0x00000000)
#define HEVC_HWPE_DEBUG_MCC_IN_LD64_mcc_in_ld64_cnt_WIDTH           (25)
#define HEVC_HWPE_DEBUG_MCC_IN_LD64_mcc_in_ld64_cnt_MASK            (0x01FFFFFF)

#endif /** _HEVC_HWPE_DEBUG_H_ */
