obj-$(CONFIG_SMP)		+= platsmp.o headsmp.o
obj-$(CONFIG_ARCH_STI) 		+= board-dt.o sti.o
obj-$(CONFIG_PERF_EVENTS)	+= st-pmu-syscfg.o
obj-$(CONFIG_SUSPEND)		+= pm/
obj-$(CONFIG_STM_PCIE_TRACKER_BUG) += io.o
obj-$(CONFIG_ST_CID_IRQMUX) 	+= cid-irqmux.o
