
#ifndef _HQVDP_MAILBOX_MACROS_H_
#define _HQVDP_MAILBOX_MACROS_H_

/****************************************************************************************
*                     Copyright STMicroelectronics
*              All rights reserved, COMPANY CONFIDENTIAL
*     Unauthorized reproduction and communication strictly prohibited
*----------------------------------------------------------------------------------------
*                   System Platforms Group - IP&Design/SPG
*----------------------------------------------------------------------------------------
*  This C header file was automatically generated by 'spirit2regtest' utility from the
*  SPIRIT description of the component.
*
*  Purpose : It declares C preprocessor definitions for component, register and
*            register fields parameters
*
*  Generated by spirit2regtest v1.7.6
*
*  PLEASE DO NOT MODIFY THIS FILE
****************************************************************************************/


/*
* Component section
* Purpose : defines macros for component
*           specific informations
*/

#define mailbox_VENDOR                                      ("st.com")
#define mailbox_LIBRARY                                     ("hqvdp")
#define mailbox_NAME                                        ("mailbox")
#define mailbox_VERSION                                     ("v1.0")

/*
* Address Block : MBX
*/

#define mailbox_MBX_BASE_ADDR                               (0x0)

/*
* Register section
* Purpose : defines macros for register and
*           its associated fields specific
*           informations
*/

/*
* Register : IRQ_TO_XP70
*/

#define mailbox_IRQ_TO_XP70_SIZE                            (32)
#define mailbox_IRQ_TO_XP70_OFFSET                          (mailbox_MBX_BASE_ADDR + 0x00)
#define mailbox_IRQ_TO_XP70_RESET_VALUE                     (0x00000000)
#define mailbox_IRQ_TO_XP70_BITFIELD_MASK                   (0x00000001)
#define mailbox_IRQ_TO_XP70_RWMASK                          (0x00000001)
#define mailbox_IRQ_TO_XP70_ROMASK                          (0x00000000)
#define mailbox_IRQ_TO_XP70_WOMASK                          (0x00000000)
#define mailbox_IRQ_TO_XP70_UNUSED_MASK                     (0xFFFFFFFE)
#define mailbox_IRQ_TO_XP70_ITTOXP70_OFFSET                 (0x00000000)
#define mailbox_IRQ_TO_XP70_ITTOXP70_WIDTH                  (1)
#define mailbox_IRQ_TO_XP70_ITTOXP70_MASK                   (0x00000001)

/*
* Register : INFO_HOST
*/

#define mailbox_INFO_HOST_SIZE                              (32)
#define mailbox_INFO_HOST_OFFSET                            (mailbox_MBX_BASE_ADDR + 0x04)
#define mailbox_INFO_HOST_RESET_VALUE                       (0x00000000)
#define mailbox_INFO_HOST_BITFIELD_MASK                     (0xFFFFFFFF)
#define mailbox_INFO_HOST_RWMASK                            (0xFFFFFFFF)
#define mailbox_INFO_HOST_ROMASK                            (0x00000000)
#define mailbox_INFO_HOST_WOMASK                            (0x00000000)
#define mailbox_INFO_HOST_UNUSED_MASK                       (0x00000000)
#define mailbox_INFO_HOST_INFO_REGISTER_HOST_OFFSET         (0x00000000)
#define mailbox_INFO_HOST_INFO_REGISTER_HOST_WIDTH          (32)
#define mailbox_INFO_HOST_INFO_REGISTER_HOST_MASK           (0xFFFFFFFF)

/*
* Register : IRQ_TO_HOST
*/

#define mailbox_IRQ_TO_HOST_SIZE                            (32)
#define mailbox_IRQ_TO_HOST_OFFSET                          (mailbox_MBX_BASE_ADDR + 0x08)
#define mailbox_IRQ_TO_HOST_RESET_VALUE                     (0x00000000)
#define mailbox_IRQ_TO_HOST_BITFIELD_MASK                   (0x00000001)
#define mailbox_IRQ_TO_HOST_RWMASK                          (0x00000001)
#define mailbox_IRQ_TO_HOST_ROMASK                          (0x00000000)
#define mailbox_IRQ_TO_HOST_WOMASK                          (0x00000000)
#define mailbox_IRQ_TO_HOST_UNUSED_MASK                     (0xFFFFFFFE)
#define mailbox_IRQ_TO_HOST_IT_TO_HOST_OFFSET               (0x00000000)
#define mailbox_IRQ_TO_HOST_IT_TO_HOST_WIDTH                (1)
#define mailbox_IRQ_TO_HOST_IT_TO_HOST_MASK                 (0x00000001)

/*
* Register : INFO_XP70
*/

#define mailbox_INFO_XP70_SIZE                              (32)
#define mailbox_INFO_XP70_OFFSET                            (mailbox_MBX_BASE_ADDR + 0x0C)
#define mailbox_INFO_XP70_RESET_VALUE                       (0x00000000)
#define mailbox_INFO_XP70_BITFIELD_MASK                     (0xFFFFFFFF)
#define mailbox_INFO_XP70_RWMASK                            (0xFFFFFFFF)
#define mailbox_INFO_XP70_ROMASK                            (0x00000000)
#define mailbox_INFO_XP70_WOMASK                            (0x00000000)
#define mailbox_INFO_XP70_UNUSED_MASK                       (0x00000000)
#define mailbox_INFO_XP70_INFO_REGISTER_XP70_OFFSET         (0x00000000)
#define mailbox_INFO_XP70_INFO_REGISTER_XP70_WIDTH          (32)
#define mailbox_INFO_XP70_INFO_REGISTER_XP70_MASK           (0xFFFFFFFF)

/*
* Register : SW_RESET_CTRL
*/

#define mailbox_SW_RESET_CTRL_SIZE                          (32)
#define mailbox_SW_RESET_CTRL_OFFSET                        (mailbox_MBX_BASE_ADDR + 0x10)
#define mailbox_SW_RESET_CTRL_RESET_VALUE                   (0x00000000)
#define mailbox_SW_RESET_CTRL_BITFIELD_MASK                 (0x00000003)
#define mailbox_SW_RESET_CTRL_RWMASK                        (0x00000000)
#define mailbox_SW_RESET_CTRL_ROMASK                        (0x00000000)
#define mailbox_SW_RESET_CTRL_WOMASK                        (0x00000003)
#define mailbox_SW_RESET_CTRL_UNUSED_MASK                   (0xFFFFFFFC)
#define mailbox_SW_RESET_CTRL_SW_RESET_FULL_OFFSET          (0x00000000)
#define mailbox_SW_RESET_CTRL_SW_RESET_FULL_WIDTH           (1)
#define mailbox_SW_RESET_CTRL_SW_RESET_FULL_MASK            (0x00000001)
#define mailbox_SW_RESET_CTRL_SW_RESET_CORE_OFFSET          (0x00000001)
#define mailbox_SW_RESET_CTRL_SW_RESET_CORE_WIDTH           (1)
#define mailbox_SW_RESET_CTRL_SW_RESET_CORE_MASK            (0x00000002)

/*
* Register : STARTUP_CTRL_1
*/

#define mailbox_STARTUP_CTRL_1_SIZE                         (32)
#define mailbox_STARTUP_CTRL_1_OFFSET                       (mailbox_MBX_BASE_ADDR + 0x14)
#define mailbox_STARTUP_CTRL_1_RESET_VALUE                  (0x00000000)
#define mailbox_STARTUP_CTRL_1_BITFIELD_MASK                (0x000003FF)
#define mailbox_STARTUP_CTRL_1_RWMASK                       (0x00000184)
#define mailbox_STARTUP_CTRL_1_ROMASK                       (0x0000027B)
#define mailbox_STARTUP_CTRL_1_WOMASK                       (0x00000000)
#define mailbox_STARTUP_CTRL_1_UNUSED_MASK                  (0xFFFFFC00)
#define mailbox_STARTUP_CTRL_1_XP70_RESET_DONE_OFFSET       (0x00000000)
#define mailbox_STARTUP_CTRL_1_XP70_RESET_DONE_WIDTH        (1)
#define mailbox_STARTUP_CTRL_1_XP70_RESET_DONE_MASK         (0x00000001)
#define mailbox_STARTUP_CTRL_1_IDLE_REQ_CAPTURE_OFFSET      (0x00000001)
#define mailbox_STARTUP_CTRL_1_IDLE_REQ_CAPTURE_WIDTH       (1)
#define mailbox_STARTUP_CTRL_1_IDLE_REQ_CAPTURE_MASK        (0x00000002)
#define mailbox_STARTUP_CTRL_1_IDLE_REQ_CAPTURE_B_0x0       (0x00000000)
#define mailbox_STARTUP_CTRL_1_IDLE_REQ_CAPTURE_B_0x1       (0x00000001)
#define mailbox_STARTUP_CTRL_1_AUTHORIZE_IDLE_MODE_OFFSET   (0x00000002)
#define mailbox_STARTUP_CTRL_1_AUTHORIZE_IDLE_MODE_WIDTH    (1)
#define mailbox_STARTUP_CTRL_1_AUTHORIZE_IDLE_MODE_MASK     (0x00000004)
#define mailbox_STARTUP_CTRL_1_AUTHORIZE_IDLE_MODE_B_0x0    (0x00000000)
#define mailbox_STARTUP_CTRL_1_AUTHORIZE_IDLE_MODE_B_0x1    (0x00000001)
#define mailbox_STARTUP_CTRL_1_IDLE_STATUS_OFFSET           (0x00000003)
#define mailbox_STARTUP_CTRL_1_IDLE_STATUS_WIDTH            (4)
#define mailbox_STARTUP_CTRL_1_IDLE_STATUS_MASK             (0x00000078)
#define mailbox_STARTUP_CTRL_1_IDLE_STATUS_B_0x0            (0x00000000)
#define mailbox_STARTUP_CTRL_1_IDLE_STATUS_B_0x1            (0x00000001)
#define mailbox_STARTUP_CTRL_1_IDLE_STATUS_B_0x2            (0x00000002)
#define mailbox_STARTUP_CTRL_1_IDLE_STATUS_B_0x4            (0x00000004)
#define mailbox_STARTUP_CTRL_1_IDLE_STATUS_B_0x8            (0x00000008)
#define mailbox_STARTUP_CTRL_1_WAKEUP_OFFSET                (0x00000007)
#define mailbox_STARTUP_CTRL_1_WAKEUP_WIDTH                 (1)
#define mailbox_STARTUP_CTRL_1_WAKEUP_MASK                  (0x00000080)
#define mailbox_STARTUP_CTRL_1_WAKEUP_B_0x0                 (0x00000000)
#define mailbox_STARTUP_CTRL_1_WAKEUP_B_0x1                 (0x00000001)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_FOR_DEBUG_OFFSET   (0x00000008)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_FOR_DEBUG_WIDTH    (1)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_FOR_DEBUG_MASK     (0x00000100)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_FOR_DEBUG_B_0x0    (0x00000000)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_FOR_DEBUG_B_0x1    (0x00000001)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_ACK_OFFSET         (0x00000009)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_ACK_WIDTH          (1)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_ACK_MASK           (0x00000200)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_ACK_B_0x0          (0x00000000)
#define mailbox_STARTUP_CTRL_1_EMUL_MODE_ACK_B_0x1          (0x00000001)

/*
* Register : STARTUP_CTRL_2
*/

#define mailbox_STARTUP_CTRL_2_SIZE                         (32)
#define mailbox_STARTUP_CTRL_2_OFFSET                       (mailbox_MBX_BASE_ADDR + 0x18)
#define mailbox_STARTUP_CTRL_2_RESET_VALUE                  (0x00000000)
#define mailbox_STARTUP_CTRL_2_BITFIELD_MASK                (0x00000003)
#define mailbox_STARTUP_CTRL_2_RWMASK                       (0x00000003)
#define mailbox_STARTUP_CTRL_2_ROMASK                       (0x00000000)
#define mailbox_STARTUP_CTRL_2_WOMASK                       (0x00000000)
#define mailbox_STARTUP_CTRL_2_UNUSED_MASK                  (0xFFFFFFFC)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_AUTO_OFFSET         (0x00000000)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_AUTO_WIDTH          (1)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_AUTO_MASK           (0x00000001)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_AUTO_B_0x0          (0x00000000)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_AUTO_B_0x1          (0x00000001)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_OFFSET              (0x00000001)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_WIDTH               (1)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_MASK                (0x00000002)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_B_0x0               (0x00000000)
#define mailbox_STARTUP_CTRL_2_FETCH_EN_B_0x1               (0x00000001)

/*
* Register : GP_STATUS
*/

#define mailbox_GP_STATUS_SIZE                              (32)
#define mailbox_GP_STATUS_OFFSET                            (mailbox_MBX_BASE_ADDR + 0x1C)
#define mailbox_GP_STATUS_RESET_VALUE                       (0x00000000)
#define mailbox_GP_STATUS_BITFIELD_MASK                     (0xFFFFFFFF)
#define mailbox_GP_STATUS_RWMASK                            (0xFFFFFFFF)
#define mailbox_GP_STATUS_ROMASK                            (0x00000000)
#define mailbox_GP_STATUS_WOMASK                            (0x00000000)
#define mailbox_GP_STATUS_UNUSED_MASK                       (0x00000000)
#define mailbox_GP_STATUS_GP_STATUS_OFFSET                  (0x00000000)
#define mailbox_GP_STATUS_GP_STATUS_WIDTH                   (32)
#define mailbox_GP_STATUS_GP_STATUS_MASK                    (0xFFFFFFFF)

/*
* Register : NEXT_CMD
*/

#define mailbox_NEXT_CMD_SIZE                               (32)
#define mailbox_NEXT_CMD_OFFSET                             (mailbox_MBX_BASE_ADDR + 0x20)
#define mailbox_NEXT_CMD_RESET_VALUE                        (0x00000000)
#define mailbox_NEXT_CMD_BITFIELD_MASK                      (0xFFFFFFFF)
#define mailbox_NEXT_CMD_RWMASK                             (0xFFFFFFFF)
#define mailbox_NEXT_CMD_ROMASK                             (0x00000000)
#define mailbox_NEXT_CMD_WOMASK                             (0x00000000)
#define mailbox_NEXT_CMD_UNUSED_MASK                        (0x00000000)
#define mailbox_NEXT_CMD_NEXT_CMD_OFFSET                    (0x00000000)
#define mailbox_NEXT_CMD_NEXT_CMD_WIDTH                     (32)
#define mailbox_NEXT_CMD_NEXT_CMD_MASK                      (0xFFFFFFFF)

/*
* Register : CURRENT_CMD
*/

#define mailbox_CURRENT_CMD_SIZE                            (32)
#define mailbox_CURRENT_CMD_OFFSET                          (mailbox_MBX_BASE_ADDR + 0x24)
#define mailbox_CURRENT_CMD_RESET_VALUE                     (0x00000000)
#define mailbox_CURRENT_CMD_BITFIELD_MASK                   (0xFFFFFFFF)
#define mailbox_CURRENT_CMD_RWMASK                          (0x00000000)
#define mailbox_CURRENT_CMD_ROMASK                          (0xFFFFFFFF)
#define mailbox_CURRENT_CMD_WOMASK                          (0x00000000)
#define mailbox_CURRENT_CMD_UNUSED_MASK                     (0x00000000)
#define mailbox_CURRENT_CMD_CURRENT_CMD_OFFSET              (0x00000000)
#define mailbox_CURRENT_CMD_CURRENT_CMD_WIDTH               (32)
#define mailbox_CURRENT_CMD_CURRENT_CMD_MASK                (0xFFFFFFFF)

/*
* Register : SOFT_VSYNC
*/

#define mailbox_SOFT_VSYNC_SIZE                             (32)
#define mailbox_SOFT_VSYNC_OFFSET                           (mailbox_MBX_BASE_ADDR + 0x28)
#define mailbox_SOFT_VSYNC_RESET_VALUE                      (0x00000000)
#define mailbox_SOFT_VSYNC_BITFIELD_MASK                    (0x10000133)
#define mailbox_SOFT_VSYNC_RWMASK                           (0x00000123)
#define mailbox_SOFT_VSYNC_ROMASK                           (0x10000010)
#define mailbox_SOFT_VSYNC_WOMASK                           (0x00000000)
#define mailbox_SOFT_VSYNC_UNUSED_MASK                      (0xEFFFFECC)
#define mailbox_SOFT_VSYNC_VSYNC_MODE_OFFSET                (0x00000000)
#define mailbox_SOFT_VSYNC_VSYNC_MODE_WIDTH                 (2)
#define mailbox_SOFT_VSYNC_VSYNC_MODE_MASK                  (0x00000003)
#define mailbox_SOFT_VSYNC_VSYNC_MODE_B_0x0                 (0x00000000)
#define mailbox_SOFT_VSYNC_VSYNC_MODE_B_0x1                 (0x00000001)
#define mailbox_SOFT_VSYNC_CMD_PENDING_OFFSET               (0x00000004)
#define mailbox_SOFT_VSYNC_CMD_PENDING_WIDTH                (1)
#define mailbox_SOFT_VSYNC_CMD_PENDING_MASK                 (0x00000010)
#define mailbox_SOFT_VSYNC_CMD_ONGOING_OFFSET               (0x00000005)
#define mailbox_SOFT_VSYNC_CMD_ONGOING_WIDTH                (1)
#define mailbox_SOFT_VSYNC_CMD_ONGOING_MASK                 (0x00000020)
#define mailbox_SOFT_VSYNC_SW_VSYNC_CTRL_OFFSET             (0x00000008)
#define mailbox_SOFT_VSYNC_SW_VSYNC_CTRL_WIDTH              (1)
#define mailbox_SOFT_VSYNC_SW_VSYNC_CTRL_MASK               (0x00000100)
#define mailbox_SOFT_VSYNC_VSYNC_STATUS_OFFSET              (0x0000001c)
#define mailbox_SOFT_VSYNC_VSYNC_STATUS_WIDTH               (1)
#define mailbox_SOFT_VSYNC_VSYNC_STATUS_MASK                (0x10000000)

#endif /* _MAILBOX_H_ */
