
#ifndef _PLUG_RDREGBANK_H_
#define _PLUG_RDREGBANK_H_

/****************************************************************************************
*                     Copyright STMicroelectronics
*              All rights reserved, COMPANY CONFIDENTIAL
*     Unauthorized reproduction and communication strictly prohibited
*----------------------------------------------------------------------------------------
*                   System Platforms Group - IP&Design/SPG
*----------------------------------------------------------------------------------------
*  This C header file was automatically generated by 'spirit2regtest' utility from the
*  SPIRIT description of the component.
*
*  Purpose : It declares C preprocessor definitions for component, register and 
*            register fields parameters
*
*  Generated by spirit2regtest v1.7.6
*
*  PLEASE DO NOT MODIFY THIS FILE
****************************************************************************************/


/*
* Component section
* Purpose : defines macros for component
*           specific informations
*/

#define PLUG_RDregBank_VENDOR                               ("st.com")
#define PLUG_RDregBank_LIBRARY                              ("hqvdp")
#define PLUG_RDregBank_NAME                                 ("PLUG_RDregBank")
#define PLUG_RDregBank_VERSION                              ("v1.0")

/*
* Address Block : READPLUG
*/

#define PLUG_RDregBank_READPLUG_BASE_ADDR                   (0x1000)

/*
* Register section
* Purpose : defines macros for register and
*           its associated fields specific
*           informations
*/

/*
* Register : CONTROL
*/

#define PLUG_RDregBank_CONTROL_SIZE                         (32)
#define PLUG_RDregBank_CONTROL_OFFSET                       (PLUG_RDregBank_READPLUG_BASE_ADDR + 0x00)
#define PLUG_RDregBank_CONTROL_RESET_VALUE                  (0x000)
#define PLUG_RDregBank_CONTROL_BITFIELD_MASK                (0x00000003)
#define PLUG_RDregBank_CONTROL_RWMASK                       (0x00000001)
#define PLUG_RDregBank_CONTROL_ROMASK                       (0x00000002)
#define PLUG_RDregBank_CONTROL_WOMASK                       (0x00000000)
#define PLUG_RDregBank_CONTROL_UNUSED_MASK                  (0xFFFFFFFC)
#define PLUG_RDregBank_CONTROL_ENABLE_OFFSET                (0x00000000)
#define PLUG_RDregBank_CONTROL_ENABLE_WIDTH                 (1)
#define PLUG_RDregBank_CONTROL_ENABLE_MASK                  (0x00000001)
#define PLUG_RDregBank_CONTROL_BUSY_OFFSET                  (0x00000001)
#define PLUG_RDregBank_CONTROL_BUSY_WIDTH                   (1)
#define PLUG_RDregBank_CONTROL_BUSY_MASK                    (0x00000002)

/*
* Register : PAGE_SIZE
*/

#define PLUG_RDregBank_PAGE_SIZE_SIZE                       (32)
#define PLUG_RDregBank_PAGE_SIZE_OFFSET                     (PLUG_RDregBank_READPLUG_BASE_ADDR + 0x04)
#define PLUG_RDregBank_PAGE_SIZE_RESET_VALUE                (0x000)
#define PLUG_RDregBank_PAGE_SIZE_BITFIELD_MASK              (0x0000000F)
#define PLUG_RDregBank_PAGE_SIZE_RWMASK                     (0x0000000F)
#define PLUG_RDregBank_PAGE_SIZE_ROMASK                     (0x00000000)
#define PLUG_RDregBank_PAGE_SIZE_WOMASK                     (0x00000000)
#define PLUG_RDregBank_PAGE_SIZE_UNUSED_MASK                (0xFFFFFFF0)
#define PLUG_RDregBank_PAGE_SIZE_PAGE_SIZE_OFFSET           (0x00000000)
#define PLUG_RDregBank_PAGE_SIZE_PAGE_SIZE_WIDTH            (4)
#define PLUG_RDregBank_PAGE_SIZE_PAGE_SIZE_MASK             (0x0000000F)

/*
* Register : MIN_OPC
*/

#define PLUG_RDregBank_MIN_OPC_SIZE                         (32)
#define PLUG_RDregBank_MIN_OPC_OFFSET                       (PLUG_RDregBank_READPLUG_BASE_ADDR + 0x08)
#define PLUG_RDregBank_MIN_OPC_RESET_VALUE                  (0x000)
#define PLUG_RDregBank_MIN_OPC_BITFIELD_MASK                (0x00000007)
#define PLUG_RDregBank_MIN_OPC_RWMASK                       (0x00000007)
#define PLUG_RDregBank_MIN_OPC_ROMASK                       (0x00000000)
#define PLUG_RDregBank_MIN_OPC_WOMASK                       (0x00000000)
#define PLUG_RDregBank_MIN_OPC_UNUSED_MASK                  (0xFFFFFFF8)
#define PLUG_RDregBank_MIN_OPC_MIN_OPC_OFFSET               (0x00000000)
#define PLUG_RDregBank_MIN_OPC_MIN_OPC_WIDTH                (3)
#define PLUG_RDregBank_MIN_OPC_MIN_OPC_MASK                 (0x00000007)

/*
* Register : MAX_OPC
*/

#define PLUG_RDregBank_MAX_OPC_SIZE                         (32)
#define PLUG_RDregBank_MAX_OPC_OFFSET                       (PLUG_RDregBank_READPLUG_BASE_ADDR + 0x0C)
#define PLUG_RDregBank_MAX_OPC_RESET_VALUE                  (0x000)
#define PLUG_RDregBank_MAX_OPC_BITFIELD_MASK                (0x00000007)
#define PLUG_RDregBank_MAX_OPC_RWMASK                       (0x00000007)
#define PLUG_RDregBank_MAX_OPC_ROMASK                       (0x00000000)
#define PLUG_RDregBank_MAX_OPC_WOMASK                       (0x00000000)
#define PLUG_RDregBank_MAX_OPC_UNUSED_MASK                  (0xFFFFFFF8)
#define PLUG_RDregBank_MAX_OPC_MAX_OPC_OFFSET               (0x00000000)
#define PLUG_RDregBank_MAX_OPC_MAX_OPC_WIDTH                (3)
#define PLUG_RDregBank_MAX_OPC_MAX_OPC_MASK                 (0x00000007)

/*
* Register : MAX_CHK
*/

#define PLUG_RDregBank_MAX_CHK_SIZE                         (32)
#define PLUG_RDregBank_MAX_CHK_OFFSET                       (PLUG_RDregBank_READPLUG_BASE_ADDR + 0x10)
#define PLUG_RDregBank_MAX_CHK_RESET_VALUE                  (0x000)
#define PLUG_RDregBank_MAX_CHK_BITFIELD_MASK                (0x00000007)
#define PLUG_RDregBank_MAX_CHK_RWMASK                       (0x00000007)
#define PLUG_RDregBank_MAX_CHK_ROMASK                       (0x00000000)
#define PLUG_RDregBank_MAX_CHK_WOMASK                       (0x00000000)
#define PLUG_RDregBank_MAX_CHK_UNUSED_MASK                  (0xFFFFFFF8)
#define PLUG_RDregBank_MAX_CHK_MAX_CHK_OFFSET               (0x00000000)
#define PLUG_RDregBank_MAX_CHK_MAX_CHK_WIDTH                (3)
#define PLUG_RDregBank_MAX_CHK_MAX_CHK_MASK                 (0x00000007)

/*
* Register : MAX_MSG
*/

#define PLUG_RDregBank_MAX_MSG_SIZE                         (32)
#define PLUG_RDregBank_MAX_MSG_OFFSET                       (PLUG_RDregBank_READPLUG_BASE_ADDR + 0x14)
#define PLUG_RDregBank_MAX_MSG_RESET_VALUE                  (0x000)
#define PLUG_RDregBank_MAX_MSG_BITFIELD_MASK                (0x00000007)
#define PLUG_RDregBank_MAX_MSG_RWMASK                       (0x00000007)
#define PLUG_RDregBank_MAX_MSG_ROMASK                       (0x00000000)
#define PLUG_RDregBank_MAX_MSG_WOMASK                       (0x00000000)
#define PLUG_RDregBank_MAX_MSG_UNUSED_MASK                  (0xFFFFFFF8)
#define PLUG_RDregBank_MAX_MSG_MAX_MSG_OFFSET               (0x00000000)
#define PLUG_RDregBank_MAX_MSG_MAX_MSG_WIDTH                (3)
#define PLUG_RDregBank_MAX_MSG_MAX_MSG_MASK                 (0x00000007)

/*
* Register : MIN_SPACE
*/

#define PLUG_RDregBank_MIN_SPACE_SIZE                       (32)
#define PLUG_RDregBank_MIN_SPACE_OFFSET                     (PLUG_RDregBank_READPLUG_BASE_ADDR + 0x18)
#define PLUG_RDregBank_MIN_SPACE_RESET_VALUE                (0x000)
#define PLUG_RDregBank_MIN_SPACE_BITFIELD_MASK              (0x0000FFFF)
#define PLUG_RDregBank_MIN_SPACE_RWMASK                     (0x0000FFFF)
#define PLUG_RDregBank_MIN_SPACE_ROMASK                     (0x00000000)
#define PLUG_RDregBank_MIN_SPACE_WOMASK                     (0x00000000)
#define PLUG_RDregBank_MIN_SPACE_UNUSED_MASK                (0xFFFF0000)
#define PLUG_RDregBank_MIN_SPACE_MIN_SPACE_OFFSET           (0x00000000)
#define PLUG_RDregBank_MIN_SPACE_MIN_SPACE_WIDTH            (16)
#define PLUG_RDregBank_MIN_SPACE_MIN_SPACE_MASK             (0x0000FFFF)

#endif /* _PLUG_RDREGBANK_H_ */
