.TH "gen_system_runlevel.sh" "8" "" "" ""
.SH "ИМЯ"
gen_system_runlevel.sh \- создаёт уровни запуска initng
.SH "СИНТАКСИС"
\fBgen_system_runlevel.sh\fR [\fIкаталог\fR]
.SH "ОПИСАНИЕ"
\fBgen_system_runlevel.sh\fR создаёт уровни запуска используемые initng. Существуют \fIdefault.runlevel\fR, \fIsystem.runlevel\fR и \fIup.runlevel\fR. Если вы не указали другой каталог они создаются в /etc/initng.
.SH "ОПЦИИ"
.TP 
\fBdirectory\fR
Если вы указали каталог, файлы будут записаны в \fIкаталог/etc/initng\fR.
.SH "СМ. ТАКЖЕ"
.BR initng(8),
.BR ngc(8),
.BR ngdc(8),
.BR ng\-update(8),
.BR install_service(8),
.BR system_off(8).
.SH "АВТОРЫ"
initng был написан Джимми Веннланд (Jimmy Wennlund) <jimmy.wennlund@gmail.com> и может быть найден на http://www.initng.org/.
.PP 
Эта страничка была написана Армен Беррес (Armin Berres) <a.berres@web.de> и основана на файле readme написанном
Патриком Боенке (Patrick Boehnke).
.PP
Автор русского перевода Чистов Владимир <vlmr@yanex.ru>
