player-objs :=  player_coded_frame.o \
		player_construct.o \
		player_events.o \
		player_extraction.o \
		player_in_sequence.o \
		player_input.o \
		player_playback.o \
		player_process_collate_to_parse.o \
		player_process_decode_to_manifest.o \
		player_process_parse_to_decode.o \
		player_process_post_manifest.o \
		player_settings.o \
		player_statistics.o \
		player_switch.o \
		player_time.o

obj-y += $(player-objs)

