# STI platform support

snd-soc-sti-mach-objs := uniperif_player.o uniperif_reader.o
snd-soc-sti-mach-objs += sti_backend.o sti_frontend.o

obj-$(CONFIG_SND_SOC_STI) += uniperif_player.o
obj-$(CONFIG_SND_SOC_STI) += uniperif_reader.o
obj-$(CONFIG_SND_SOC_STI) += sti_backend.o
obj-$(CONFIG_SND_SOC_STI) += sti_frontend.o