SCRIPTS_PATH ?= ../Tools/Scripts
XCODE_OPTIONS = `perl -I$(SCRIPTS_PATH) -Mwebkitdirs -e 'print XcodeOptionString()'` $(ARGS)

all: force

debug d development dev develop: force

release r deployment dep deploy: force

clean: force

force: ;
