obj-$(CONFIG_LIBELF_32) += libelf_32.o

libelf_32-objs := libelf_32-info.o libelf_32-load.o libelf_32-main.o

obj-$(CONFIG_LIBELF_64) += libelf_64.o

libelf_64-objs := libelf_64-info.o libelf_64-load.o libelf_64-main.o
