/************************************************************************
Copyright (C) 2011 STMicroelectronics. All Rights Reserved.

This file is part of the Transport Engine Library.

The Transport Engine is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 2 as
published by the Free Software Foundation.

Transport Engine is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with Transport Engine; see the file COPYING.  If not, write to the Free
Software Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307,
USA.

The Transport Engine Library may alternatively be licensed under a
proprietary license from ST.

************************************************************************/
/**
   @file   pti_stpti.h
   @brief  Provides a restricted interface stpti.h

   This includes the stapi types by defining _stptiHAL_ not the  used by the te HAL.

 */

#if !defined( _PTI_STPTI_H_ ) && !defined( _STPTI_H_ )
#define _PTI_STPTI_H_

#define _stptiHAL_
#include "stddefs.h"

typedef enum STPTI_ErrorType_s {
	/* 0x101 */ STPTI_ERROR_ALREADY_WAITING_ON_SLOT = 0x101,
	/* 0x102 */ STPTI_ERROR_BUFFER_NOT_LINKED,
	/* 0x103 */ STPTI_ERROR_CAROUSEL_ALREADY_ALLOCATED,
	/* 0x104 */ STPTI_ERROR_CAROUSEL_ENTRY_INSERTED,
	/* 0x105 */ STPTI_ERROR_CAROUSEL_LOCKED_BY_DIFFERENT_SESSION,
	/* 0x106 */ STPTI_ERROR_CAROUSEL_NOT_LOCKED,
	/* 0x107 */ STPTI_ERROR_CAROUSEL_OUTPUT_ONLY_ON_NULL_SLOT,
	/* 0x108 */ STPTI_ERROR_CORRUPT_DATA_IN_BUFFER,
	/* 0x109 */ STPTI_ERROR_DESCRAMBLER_ALREADY_ASSOCIATED,
	/* 0x10a */ STPTI_ERROR_DESCRAMBLER_NOT_ASSOCIATED,
	/* 0x10b */ STPTI_ERROR_DESCRAMBLER_TYPE_NOT_SUPPORTED,
	/* 0x10c */ STPTI_ERROR_DMA_UNAVAILABLE,
	/* 0x10d */ STPTI_ERROR_ENTRY_ALREADY_INSERTED,
	/* 0x10e */ STPTI_ERROR_ENTRY_IN_USE,
	/* 0x10f */ STPTI_ERROR_ENTRY_NOT_IN_CAROUSEL,
	/* 0x110 */ STPTI_ERROR_EVENT_QUEUE_EMPTY,
	/* 0x111 */ STPTI_ERROR_EVENT_QUEUE_FULL,
	/* 0x112 */ STPTI_ERROR_FILTER_ALREADY_ASSOCIATED,
	/* 0x113 */ STPTI_ERROR_FLUSH_FILTERS_NOT_SUPPORTED,
	/* 0x114 */ STPTI_ERROR_FUNCTION_NOT_SUPPORTED,
	/* 0x115 */ STPTI_ERROR_INCOMPLETE_PES_IN_BUFFER,
	/* 0x116 */ STPTI_ERROR_INCOMPLETE_SECTION_IN_BUFFER,
	/* 0x117 */ STPTI_ERROR_INDEX_INVALID_ASSOCIATION,
	/* 0x118 */ STPTI_ERROR_INDEX_INVALID_HANDLE,
	/* 0x119 */ STPTI_ERROR_INDEX_NONE_FREE,
	/* 0x11a */ STPTI_ERROR_INDEX_NOT_ASSOCIATED,
	/* 0x11b */ STPTI_ERROR_INDEX_PID_ALREADY_ASSOCIATED,
	/* 0x11c */ STPTI_ERROR_INDEX_SLOT_ALREADY_ASSOCIATED,
	/* 0x11d */ STPTI_ERROR_INTERRUPT_QUEUE_EMPTY,
	/* 0x11e */ STPTI_ERROR_INTERRUPT_QUEUE_FULL,
	/* 0x11f */ STPTI_ERROR_INVALID_ALLOW_OUTPUT_TYPE,
	/* 0x120 */ STPTI_ERROR_INVALID_BUFFER_HANDLE,
	/* 0x121 */ STPTI_ERROR_INVALID_CAROUSEL_ENTRY_HANDLE,
	/* 0x122 */ STPTI_ERROR_INVALID_CAROUSEL_HANDLE,
	/* 0x123 */ STPTI_ERROR_INVALID_CD_FIFO_ADDRESS,
	/* 0x124 */ STPTI_ERROR_INVALID_DESCRAMBLER_ASSOCIATION,
	/* 0x125 */ STPTI_ERROR_INVALID_DESCRAMBLER_HANDLE,
	/* 0x126 */ STPTI_ERROR_INVALID_DEVICE,
	/* 0x127 */ STPTI_ERROR_INVALID_FILTER_DATA,
	/* 0x128 */ STPTI_ERROR_INVALID_FILTER_HANDLE,
	/* 0x129 */ STPTI_ERROR_INVALID_FILTER_OPERATING_MODE,
	/* 0x12a */ STPTI_ERROR_INVALID_FILTER_REPEAT_MODE,
	/* 0x12b */ STPTI_ERROR_INVALID_FILTER_TYPE,
	/* 0x12c */ STPTI_ERROR_INVALID_INJECTION_TYPE,
	/* 0x12d */ STPTI_ERROR_INVALID_KEY_USAGE,
	/* 0x12e */ STPTI_ERROR_INVALID_LOADER_OPTIONS,
	/* 0x12f */ STPTI_ERROR_INVALID_PARITY,
	/* 0x130 */ STPTI_ERROR_INVALID_PES_START_CODE,
	/* 0x131 */ STPTI_ERROR_INVALID_PID,
	/* 0x132 */ STPTI_ERROR_INVALID_SESSION_HANDLE,
	/* 0x133 */ STPTI_ERROR_INVALID_SIGNAL_HANDLE,
	/* 0x134 */ STPTI_ERROR_INVALID_SLOT_HANDLE,
	/* 0x135 */ STPTI_ERROR_INVALID_SLOT_TYPE,
	/* 0x136 */ STPTI_ERROR_INVALID_SUPPORTED_TC_CODE,
	/* 0x137 */ STPTI_ERROR_NOT_ALLOCATED_IN_SAME_SESSION,
	/* 0x138 */ STPTI_ERROR_NOT_INITIALISED,
	/* 0x139 */ STPTI_ERROR_NOT_ON_SAME_DEVICE,
	/* 0x13a */ STPTI_ERROR_NOT_SUPPORTED_FOR_DTV,
	/* 0x13b */ STPTI_ERROR_NO_FREE_DESCRAMBLERS,
	/* 0x13c */ STPTI_ERROR_NO_FREE_DMAS,
	/* 0x13d */ STPTI_ERROR_NO_FREE_FILTERS,
	/* 0x13e */ STPTI_ERROR_NO_FREE_SLOTS,
	/* 0x13f */ STPTI_ERROR_NO_PACKET,
	/* 0x140 */ STPTI_ERROR_OFFSET_EXCEEDS_PACKET_SIZE,
	/* 0x141 */ STPTI_ERROR_ONLY_ONE_SIGNAL_PER_BUFFER,
	/* 0x142 */ STPTI_ERROR_ONLY_ONE_SIGNAL_PER_SLOT,
	/* 0x143 */ STPTI_ERROR_PID_ALREADY_COLLECTED,
	/* 0x144 */ STPTI_ERROR_SET_MATCH_ACTION_NOT_SUPPORTED,
	/* 0x145 */ STPTI_ERROR_SIGNAL_ABORTED,
	/* 0x146 */ STPTI_ERROR_SIGNAL_EVERY_PACKET_ONLY_ON_PES_SLOT,
	/* 0x147 */ STPTI_ERROR_SLOT_FLAG_NOT_SUPPORTED,
	/* 0x148 */ STPTI_ERROR_SLOT_NOT_ASSOCIATED,
	/* 0x149 */ STPTI_ERROR_SLOT_NOT_RAW_MODE,
	/* 0x14a */ STPTI_ERROR_SLOT_NOT_SIGNAL_EVERY_PACKET,
	/* 0x14b */ STPTI_ERROR_STORE_LAST_HEADER_ONLY_ON_RAW_SLOT,
	/* 0x14c */ STPTI_ERROR_UNABLE_TO_ENABLE_FILTERS,
	/* 0x14d */ STPTI_ERROR_USER_BUFFER_NOT_ALIGNED,
	/* 0x14e */ STPTI_ERROR_WILDCARD_PID_ALREADY_SET,
	/* 0x14f */ STPTI_ERROR_WILDCARD_PID_NOT_SUPPORTED,
	/* 0x150 */ STPTI_ERROR_SLOT_ALREADY_LINKED,
	/* 0x151 */ STPTI_ERROR_NOT_A_MANUAL_BUFFER,
	/* 0x152 */ STPTI_ERROR_CAROUSEL_ENTRY_ALREADY_ALLOCATED,
	/* 0x153 */ STPTI_ERROR_IOREMAPFAILED,
	/* 0x154 */ STPTI_ERROR_INVALID_STREAM_ID,
	/* 0x155 */ STPTI_ERROR_FILTER_NOT_ASSOCIATED,
	/* 0x156 */ STPTI_ERROR_OBJECT_ALREADY_ASSOCIATED,	/* Start of new TANGO errors */
	/* 0x157 */ STPTI_ERROR_OBJECTS_NOT_ASSOCIATED,
	/* 0x158 */ STPTI_ERROR_TSINPUT_ROUTE_UNAVAILABLE,
	/* 0x159 */ STPTI_ERROR_TSINPUT_HW_ACCESS_ERROR,
	/* 0x15a */ STPTI_ERROR_TSINPUT_NOT_CONFIGURED,
	/* 0x15b */ STPTI_ERROR_BUFFER_HAS_NO_METADATA,
	/* 0x15c */ STPTI_ERROR_TOO_MANY_SLOTS_WITH_SAME_PID,
	/* 0x15d */ STPTI_ERROR_INAPPROPRIATE_API_FOR_DATA_TYPE,
	/* 0x15e */ STPTI_ERROR_INVALID_DATA_ENTRY_HANDLE,
	/* 0x15f */ STPTI_ERROR_DATA_ENTRY_ALREADY_LOADED,
	/* 0x160 */ STPTI_ERROR_DATA_ENTRY_NOT_LOADED,
	/* 0x161 */ STPTI_ERROR_NOT_ALLOWED_WHILST_PID_SET,
	/* 0x162 */ STPTI_ERROR_DIFFERING_SECURITY_PATH_IDS,
	/* 0x163 */ STPTI_ERROR_ONLY_ONE_INJECTOR_ALLOWED_ON_A_DEVICE,
	/* 0x164 */ STPTI_ERROR_ALREADY_MONITORING_PID,
	/* 0x165 */ STPTI_ERROR_NOT_MONITORING_PID,
	/* 0x166 */ STPTI_ERROR_SLOT_SECONDARY_PID_IN_USE,
	/* 0x167 */ STPTI_ERROR_NOT_ENOUGH_ROOM_TO_RETURN_DATA,
	/* 0x168 */ STPTI_ERROR_OBJECT_ASSOCIATED,
	/* 0x169 */ STPTI_ERROR_OBJECT_HAS_CHILDREN,
	/* 0x16a */ STPTI_ERROR_END	/* Must be last. This is used to determine the number of STPTI error codes. */
} STPTI_ErrorType_t;

#undef _stptiHAL_

#endif /* _PTI_STPTI_H_ */
