.TH "ngc" "8" "" "" ""
.SH "NAME"
ngc \- Next Generation init Control.
.SH "SYNOPSIS"
\fBngc\fR \-\fIh\fR
.br 
.SH "DESCRIPTION"
ngc is used to control/start/stop the services managed by initng.
.SH "OPTIONS"
The options supported by ngc depend on what plugins are loaded by running initng.
.TP 
Please execute \fBngc \-h\fR, to get a full list and description.
.br 
.SH "SEE ALSO"
.BR initng(8),
.BR ngdc(8),
.BR ng\-update(8),
.BR gen_system_runlevel(8),
.BR install_service(8),
.BR system_off(8).
.SH "AUTHOR"
initng was written by  Jimmy Wennlund <jimmy.wennlund@gmail.com> and can be found at http://www.initng.org/.
.PP 
This manual page was written by Armin Berres <a.berres@onlinehome.de.de>.
