.TH "ngc" "8" "" "" ""
.SH "NAME"
ngc \- Next Generation init Control.
.SH "SYNOPSIS"
\fBngc\fR \-\fIh\fR
.br 
.SH "DESCRIPTION"
ngdc is the same as ngc, but is controlling a faker or debug initng that does not run as pid 1.
.SH "OPTIONS"
The options that your ngdc command can do, varies to what plugins that are added.
.TP 
Please do ngdc -h, to get a full list and description.
.br 
.SH "SEE ALSO"
.BR initng(8),
.BR ngc(8),
.BR ng\-update(8),
.BR gen_system_runlevel(8),
.BR install_service(8),
.BR system_off(8).
.SH "AUTHOR"
initng was written by  Jimmy Wennlund <jimmy.wennlund@gmail.com> and can be found at http://www.initng.org/.
.PP 
This manual page was written by Armin Berres <a.berres@onlinehome.de.de>.
