#
# Makefile for the LTT objects.
#
obj-$(CONFIG_LTT)			+= ltt-timestamp.o
obj-$(CONFIG_LTT)			+= ltt-core.o
obj-$(CONFIG_LTT)			+= probes/
obj-$(CONFIG_LTT_HEARTBEAT)		+= ltt-heartbeat.o
obj-$(CONFIG_LTT_TRACER)		+= ltt-tracer.o
obj-$(CONFIG_LTT_RELAY)		+= ltt-relay.o
obj-$(CONFIG_LTT_NETLINK_CONTROL)	+= ltt-control.o
obj-$(CONFIG_LTT_SERIALIZE)		+= ltt-serialize.o
obj-$(CONFIG_LTT_STATEDUMP)		+= ltt-statedump.o
obj-$(CONFIG_LTT_TEST_TSC)		+= ltt-test-tsc.o
obj-$(CONFIG_LTT_MARKER_CONTROL)	+= ltt-marker-control.o
