/*
 * asf_guids.h
 *
 * Copyright (C) STMicroelectronics Limited 2005. All rights reserved.
 *
 * AUTOMATICALLY GENERATED - DO NOT EDIT
 */

#ifndef ASF_GUIDS_H
#define ASF_GUIDS_H


enum asf_guid_index {
	ASF_GUID_INVALID_IDENTIFIER,
	ASF_GUID_HEADER_OBJECT,
	ASF_GUID_DATA_OBJECT,
	ASF_GUID_SIMPLE_INDEX_OBJECT,
	ASF_GUID_FILE_PROPERTIES_OBJECT,
	ASF_GUID_STREAM_PROPERTIES_OBJECT,
	ASF_GUID_STREAM_BITRATE_PROPERTIES_OBJECT,
	ASF_GUID_CONTENT_DESCRIPTION_OBJECT,
	ASF_GUID_EXTENDED_CONTENT_ENCRYPTION_OBJECT,
	ASF_GUID_SCRIPT_COMMAND_OBJECT,
	ASF_GUID_MARKER_OBJECT,
	ASF_GUID_CLOCK_OBJECT,
	ASF_GUID_BITRATE_MUTUAL_EXCLUSION_OBJECT,
	ASF_GUID_CODEC_LIST_OBJECT,
	ASF_GUID_METADATA_OBJECT,
	ASF_GUID_ERROR_CORRECTION_OBJECT,
	ASF_GUID_PADDING_OBJECT,
	ASF_GUID_AUDIO_MEDIA,
	ASF_GUID_VIDEO_MEDIA,
	ASF_GUID_COMMAND_MEDIA,
	ASF_GUID_NO_ERROR_CORRECTION,
	ASF_GUID_AUDIO_SPREAD,
	ASF_GUID_MUTEX_BITRATE,
	ASF_GUID_MUTEX_UNKNOWN,
	ASF_GUID_PACKET_CLOCK_1,
	CLSID_GUID_ASFX_SIGNATURE_AUDIO_ERROR_MASKING_STRATEGY,
	ASF_GUID_MAX
};

typedef unsigned char asf_guid_t[16];
extern asf_guid_t asf_guid_lookup[ASF_GUID_MAX];
extern const char *asf_guid_name_lookup[ASF_GUID_MAX];

#endif /* ASF_GUIDS_H */

