The STLinuxTV Implementation Report is written in AsciiDoc format.

AsciiDoc (http://www.methods.co.nz/asciidoc/index.html)

In order to be built, the AsciiDoc package must be installed.
Precise information can be found at the following url:
	http://www.methods.co.nz/asciidoc/INSTALL.html

On Fedora machine, it can be very simply done by using the following command:
	yum install asciidoc dblatex

To build the documentation, run the following command from this folder:
	make all

The output is the PDF and HTML documents.

