EXTRA_CFLAGS += -I$(STG_TOPDIR)/private/include/

EXTRA_CFLAGS += -Werror

# uncomment for secure data path in display. We assume SMCS is available.
#EXTRA_CFLAGS += -DCONFIG_STM_DISPLAY_SDP -DCONFIG_STM_SMCS -I$(SDK2_SOURCE_SMCS)/include/linux

obj-m += vibe_os.o
