.TH "install_service" "8" "" "" ""
.SH "ИМЯ"
install_service \- устанавливает \fIinitng\fR файлы (.ii)
.SH "СИНТАКСИС"
\fBinstall_service\fR \fI\-\-in\fR|\fI\-i\fR [\fI\-\-out\fR|\fI\-o\fR] [\fI\-\-dist\fR|\fI\-d\fR] 
.SH "ОПИСАНИЕ"
\fBinstall_service\fR делает грамматический разбор файлов (обычно это .ii файлы) 
и устанавливает дистрибутивно-зависимые значения.
.SH "ОПЦИИ"
.TP 
\fB\-\-in, \-i\fR
Установить файл который должен быть обработан.
.TP 
\fB\-\-out, \-o\fR
Установить файл в котором нужно сохранять вывод. Если эта опция не определена вывод направляется на stdout.
.TP 
\fB\-\-dist, \-d\fR
Установить дистрибутив для которого вы хотите установить файл (например: debian, gentoo, fedora).
Если эта опция не установлена, то \fIinstall_service\fR пытается его угадать сам.
.SH "СМ. ТАКЖЕ"
.BR initng(8)
.BR ngc(8),
.BR ngdc(8),
.BR ng\-update(8),
.BR gen_system_runlevel(8),
.BR system_off(8).
.SH "АВТОРЫ"
initng был написан Джимми Веннланд (Jimmy Wennlund) <jimmy.wennlund@gmail.com> и может быть найден на http://www.initng.org/.
.PP
Эта страничка была написана Армен Беррес (Armin Berres) <a.berres@web.de> и основана на файле readme написанном
Патриком Боенке (Patrick Boehnke).
.PP
Автор русского перевода Чистов Владимир <vlmr@yanex.ru>
