frame_parser-objs:=     frame_parser_base.o \
                        frame_parser_video.o \
                        frame_parser_video_mpeg2.o \
                        frame_parser_video_h264.o \
                        frame_parser_video_vc1.o \
                        frame_parser_video_divx.o \
                        frame_parser_audio.o \
                        frame_parser_audio_aac.o \
                        frame_parser_audio_mpeg.o \
                        frame_parser_audio_lpcm.o \
                        frame_parser_audio_eac3.o \
                        frame_parser_audio_dtshd.o \
                        frame_parser_audio_wma.o \
                        asf_guids.o \
                        wma_properties.o


obj-y += $(frame_parser-objs)
