#ifndef INITNG_PATHS_H 
#define INITNG_PATHS_H

#define DEVDIR			"/dev"
#define ETCDIR			"${CMAKE_INSTALL_PREFIX}${SYSCONF_INSTALL_DIR}"
#define VARDIR			"${CMAKE_INSTALL_PREFIX}/var"
#define INITNG_ROOT		"${CMAKE_INSTALL_PREFIX}${SYSCONF_INSTALL_DIR}/initng"
#define INITNG_PLUGIN_DIR	"${CMAKE_INSTALL_PREFIX}${LIB_INSTALL_DIR}/initng"
#define RUNLEVEL_PREFIX		"${RUNLEVEL_PREFIX}"

#endif /* INITNG_PATHS_H */
