/************************************************************************
Copyright (C) 2011 STMicroelectronics. All Rights Reserved.

This file is part of the STLinuxTV Library.

STLinuxTV is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License version 2 as published by the
Free Software Foundation.

STLinuxTV is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with STLinuxTV; see the file COPYING.  If not, write to the Free Software
Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

The STLinuxTV Library may alternatively be licensed under a proprietary
license from ST.

Source file name : stm_dvb_option.h

Extensions to the LinuxDVB API (v3)

Date        Modification                                    Name
----        ------------                                    --------

 ************************************************************************/

#ifndef H_STM_DVB_OPTION
#define H_STM_DVB_OPTION


typedef enum {
#define DVB_OPTION_VALUE_DISABLE                                                        0
#define DVB_OPTION_VALUE_ENABLE                                                         1
#define DVB_OPTION_VALUE_AUTO                                                           2

	DVB_OPTION_TRICK_MODE_AUDIO = 0,
	DVB_OPTION_PLAY_24FPS_VIDEO_AT_25FPS = 1,

#define DVB_OPTION_VALUE_VIDEO_CLOCK_MASTER                                             0
#define DVB_OPTION_VALUE_AUDIO_CLOCK_MASTER                                             1
#define DVB_OPTION_VALUE_SYSTEM_CLOCK_MASTER                                            2
	DVB_OPTION_MASTER_CLOCK = 2,

	DVB_OPTION_EXTERNAL_TIME_MAPPING = 3,
	DVB_OPTION_EXTERNAL_TIME_MAPPING_VSYNC_LOCKED = 31,
	DVB_OPTION_AV_SYNC = 4,
	DVB_OPTION_DISPLAY_FIRST_FRAME_EARLY = 5,
	DVB_OPTION_VIDEO_BLANK = 6,
	DVB_OPTION_STREAM_ONLY_KEY_FRAMES = 7,
	DVB_OPTION_STREAM_SINGLE_GROUP_BETWEEN_DISCONTINUITIES = 8,
	DVB_OPTION_CLAMP_PLAYBACK_INTERVAL_ON_PLAYBACK_DIRECTION_CHANGE = 9,

#define DVB_OPTION_VALUE_PLAYOUT                                                        0
#define DVB_OPTION_VALUE_DISCARD                                                        1
	DVB_OPTION_PLAYOUT_ON_TERMINATE = 10,
	DVB_OPTION_PLAYOUT_ON_SWITCH = 11,
	DVB_OPTION_PLAYOUT_ON_DRAIN = 12,

	DVB_OPTION_VIDEO_ASPECT_RATIO = 13,
	DVB_OPTION_VIDEO_DISPLAY_FORMAT = 14,

#define DVB_OPTION_VALUE_TRICK_MODE_AUTO                                                0
#define DVB_OPTION_VALUE_TRICK_MODE_DECODE_ALL                                          1
#define DVB_OPTION_VALUE_TRICK_MODE_DECODE_ALL_DEGRADE_NON_REFERENCE_FRAMES             2
#define DVB_OPTION_VALUE_TRICK_MODE_START_DISCARDING_NON_REFERENCE_FRAMES               3
#define DVB_OPTION_VALUE_TRICK_MODE_DECODE_REFERENCE_FRAMES_DEGRADE_NON_KEY_FRAMES      4
#define DVB_OPTION_VALUE_TRICK_MODE_DECODE_KEY_FRAMES                                   5
#define DVB_OPTION_VALUE_TRICK_MODE_DISCONTINUOUS_KEY_FRAMES                            6
	DVB_OPTION_TRICK_MODE_DOMAIN = 15,

#define DVB_OPTION_VALUE_DISCARD_LATE_FRAMES_NEVER                                      0
#define DVB_OPTION_VALUE_DISCARD_LATE_FRAMES_ALWAYS                                     1
#define DVB_OPTION_VALUE_DISCARD_LATE_FRAMES_AFTER_SYNCHRONIZE                          2
	DVB_OPTION_DISCARD_LATE_FRAMES = 16,
	DVB_OPTION_VIDEO_START_IMMEDIATE = 17,
	DVB_OPTION_REBASE_ON_DATA_DELIVERY_LATE = 18,
	DVB_OPTION_REBASE_ON_FRAME_DECODE_LATE = 19,
	DVB_OPTION_LOWER_CODEC_DECODE_LIMITS_ON_FRAME_DECODE_LATE = 20,
	DVB_OPTION_H264_ALLOW_NON_IDR_RESYNCHRONIZATION = 21,
	DVB_OPTION_MPEG2_IGNORE_PROGESSIVE_FRAME_FLAG = 22,
	DVB_OPTION_AUDIO_SPDIF_SOURCE = 23,

	DVB_OPTION_H264_ALLOW_BAD_PREPROCESSED_FRAMES = 24,
	DVB_OPTION_CLOCK_RATE_ADJUSTMENT_LIMIT_2_TO_THE_N_PARTS_PER_MILLION = 25,	/* Value = N */
	DVB_OPTION_LIMIT_INPUT_INJECT_AHEAD = 26,

#define DVB_OPTION_VALUE_MPEG2_APPLICATION_MPEG2                                        0
#define DVB_OPTION_VALUE_MPEG2_APPLICATION_ATSC                                         1
#define DVB_OPTION_VALUE_MPEG2_APPLICATION_DVB                                          2
	DVB_OPTION_MPEG2_APPLICATION_TYPE = 27,

#define DVB_OPTION_VALUE_DECIMATE_DECODER_OUTPUT_DISABLED                               0
#define DVB_OPTION_VALUE_DECIMATE_DECODER_OUTPUT_HALF                                   1
#define DVB_OPTION_VALUE_DECIMATE_DECODER_OUTPUT_QUARTER                                2
	DVB_OPTION_DECIMATE_DECODER_OUTPUT = 28,

	DVB_OPTION_PTS_FORWARD_JUMP_DETECTION_THRESHOLD = 29,
	DVB_OPTION_H264_TREAT_DUPLICATE_DPB_AS_NON_REFERENCE_FRAME_FIRST = 30,

	DVB_OPTION_PIXEL_ASPECT_RATIO_CORRECTION = 32,

	DVB_OPTION_H264_FORCE_PIC_ORDER_CNT_IGNORE_DPB_DISPLAY_FRAME_ORDERING =
	    33,

	DVB_OPTION_SYMMETRIC_JUMP_DETECTION = 34,

	DVB_OPTION_ALLOW_FRAME_DISCARD_AT_NORMAL_SPEED = 35,

	DVB_OPTION_OPERATE_COLLATOR2_IN_REVERSIBLE_MODE = 36,

	DVB_OPTION_IGNORE_STREAM_UNPLAYABLE_CALLS = 38,

	DVB_OPTION_USE_PTS_DEDUCED_DEFAULT_FRAME_RATES = 39,

	DVB_OPTION_H264_TREAT_TOP_BOTTOM_PICTURE_STRUCT_AS_INTERLACED = 40,

	DVB_OPTION_H264_VALIDATE_DPB_VALUES_AGAINST_PTS_VALUES = 41,

	DVB_OPTION_LIVE_PLAY = 42,

	DVB_OPTION_RUNNING_DEVLOG = 43,

#define DVB_OPTION_VALUE_ERROR_DECODING_LEVEL_NORMAL                                    0
#define DVB_OPTION_VALUE_ERROR_DECODING_LEVEL_MAXIMUM                                   1
	DVB_OPTION_ERROR_DECODING_LEVEL = 44,

	DVB_OPTION_ALLOW_REFERENCE_FRAME_SUBSTITUTION = 45,

	DVB_OPTION_DISCARD_FOR_REFERENCE_QUALITY_THRESHOLD = 46,

	DVB_OPTION_DISCARD_FOR_MANIFESTATION_QUALITY_THRESHOLD = 47,

#define DVB_OPTION_QUALITY_THRESHOLD_MAX                                                255

	DVB_OPTION_CTRL_PLAYBACK_LATENCY = 48,

#define DVB_OPTION_CTRL_VALUE_NO_DISCARD						0
#define DVB_OPTION_CTRL_VALUE_REFERENCE_FRAMES_ONLY					1
#define DVB_OPTION_CTRL_VALUE_KEY_FRAMES_ONLY						2
	DVB_OPTION_CTRL_VIDEO_DISCARD_FRAMES = 49,

#define DVB_OPTION_VALUE_PRECEDENCE_STREAM_PTS_CONTAINER				0
#define DVB_OPTION_VALUE_PRECEDENCE_STREAM_CONTAINER_PTS				1
#define DVB_OPTION_VALUE_PRECEDENCE_PTS_STREAM_CONTAINER				2
#define DVB_OPTION_VALUE_PRECEDENCE_PTS_CONTAINER_STREAM				3
#define DVB_OPTION_VALUE_PRECEDENCE_CONTAINER_PTS_STREAM				4
#define DVB_OPTION_VALUE_PRECEDENCE_CONTAINER_STREAM_PTS				5
	DVB_OPTION_FRAME_RATE_CALCULATION_PRECEDENCE = 50,
	DVB_OPTION_PACKET_INJECTOR = 51,

#define DVB_OPTION_CTRL_VALUE_HD_PROFILE		0
#define DVB_OPTION_CTRL_VALUE_4K2K_PROFILE		1
#define DVB_OPTION_CTRL_VALUE_SD_PROFILE		2
#define DVB_OPTION_CTRL_VALUE_720P_PROFILE		3
#define DVB_OPTION_CTRL_VALUE_UHD_PROFILE		4
#define DVB_OPTION_CTRL_VALUE_HD_LEGACY_PROFILE		5
	DVB_OPTION_CTRL_VIDEO_MEMORY_PROFILE = 52,

	/* DeEmphasis : DVB_OPTION_VALUE_{DISABLE , ENABLE , AUTO} */
	DVB_OPTION_CTRL_AUDIO_DEEMPHASIS = 53,

	DVB_OPTION_CTRL_CONTAINER_FRAMERATE = 54,

	/* OPTION_MAX must always be one greater than largest option - currently DVB_OPTION_CTRL_CONTAINER_FRAMERATE */
	DVB_OPTION_MAX = 55
} dvb_option_t;

#endif /* H_DVB_OPTION */
