#
# Makefile for the phy drivers.
#

obj-$(CONFIG_GENERIC_PHY)	+= phy-core.o
obj-$(CONFIG_PHY_STIH41X_USB) 	+= phy-stih41x-usb.o
obj-$(CONFIG_PHY_MIPHY365X) 	+= phy-miphy365x.o
obj-$(CONFIG_PHY_STID127_USB) 	+= phy-stid127-usb.o
obj-$(CONFIG_PHY_MIPHY28LP) 	+= phy-miphy28lp.o
obj-$(CONFIG_PHY_STI8416_USB) 	+= phy-sti8416-usb.o
obj-$(CONFIG_PHY_STIH407_USB)	+= phy-stih407-usb.o
