codec-objs :=   codec_mme_base.o        \
		codec_mme_video.o       \
		codec_mme_video_mpeg2.o \
		codec_mme_video_h264.o \
		codec_mme_video_vc1.o \
		codec_mme_video_divx.o \
		codec_mme_audio.o \
		codec_mme_audio_stream.o \
		codec_mme_audio_aac.o \
		codec_mme_audio_mpeg.o \
		codec_mme_audio_lpcm.o \
		codec_mme_audio_wma.o \
		codec_mme_audio_eac3.o \
		codec_mme_audio_dtshd.o \
		codec_mme_audio_silence.o \
		codec_mme_audio_spdifin.o

obj-y += $(codec-objs)

