obj-$(CONFIG_ST_THERMAL)		+= st_thermal.o
st_thermal-y				:= st_thermal_common.o
st_thermal-$(CONFIG_ST_THERMAL_SYSCFG)	+= st_thermal_syscfg.o
st_thermal-$(CONFIG_ST_THERMAL_MEMMAP)	+= st_thermal_memmap.o
