EXTRA_CFLAGS+=-I$(STG_TOPDIR)/include
EXTRA_CFLAGS+=-I$(STG_TOPDIR)/linux/kernel/include
EXTRA_CFLAGS+=-I$(STG_TOPDIR)/linux/kernel/drivers/video

obj-m += vxitest.o

EXTRA_CFLAGS += -Werror

pixelcapturetest-objs := vxi.o

