KBUILD_CPPFLAGS += -I$(STM_BLITTER_TOPDIR)/linux/kernel/include
KBUILD_CPPFLAGS += -I$(STM_BLITTER_TOPDIR)/linux/kernel/drivers/stm/blitter

ccflags-y += -Wswitch-enum

gam-utils-objs := gam_utils.o surf_utils.o

obj-m += gam-utils.o
