###################################################################
# Copyright(c) 2011, Technicolor
###################################################################

# Platform ID generic code
obj-y	+= plt_id.o
# Platform ID platform specific code
obj-y	+= plt_id_specific.o

# Handle files in sysfs
obj-y	+= plt_sysfs.o

#-include arch/$(SRCARCH)/plt/Makefile.specific

